### ISSUE TITLE
NameError: name 'cmp' is not defined

### ISSUE THREAD

**Issue by whg-mtran** [search5/latlon#3]
In this library's **GeoCoord** class definition, specifically in method *_calc_degreeminutes(decimal_degree)* the Python 2.7.15 *cmp()* method is used. [*cmp()* has been removed in Python 3](https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons): 

> The cmp() function should be treated as gone, and the __cmp__() special method is no longer supported. Use __lt__() for sorting, __eq__() with __hash__(), and other rich comparisons as needed. (If you really need the cmp() functionality, you could use the expression (a > b) - (a < b) as the equivalent for cmp(a, b).)

Note that cmp() is used in this library in the _calc_decimaldegree and _calc_decimalminute methods in GeoCoord

**Comment by search5** [comment]
@whg-mtran If you upload the sample code that causes the error, I will check it and let you know.
