### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by sachingodishela** [search5/latlon#4]
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

Unable to intall

**Comment by Dawars** [comment]
Install directly from the git repo via `pip install git+https://github.com/search5/latlon/`

I haven't managed to include the lib though

**Comment by daveymg-nz** [comment]
Replying to an old post, but it may help someone:

I'm new with python and vscode but I can distill several hours of circular troubleshooting of the "README.md file not found" error into this solution that worked for me:

In your virtual environment site packages folder, create a LatLon folder. Into the LatLon folder, copy the __init__.py and lat_lon.py from this package.

After doing this, intellisense resolved the "import LatLon" statement and the methods contained in the package.

Very useful package though, provided solution to a problem I was working on, thanks.

**Comment by search5** [comment]
@sachingodishela @Dawars @daveymg-nz We have corrected it to prevent further installation errors. Sorry for the inconvenience.
